version: 2
jobs:
  MacOS:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-spm-deps-{{ checksum "Package.swift" }}
      - run:
          name: Install CMySQL and CTLS
          command: |
            brew tap vapor/homebrew-tap
            brew install cmysql
            brew install ctls
            brew install libressl
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift package generate-xcodeproj --enable-code-coverage    
            xcodebuild -scheme AdminPanel-Package -enableCodeCoverage YES test | xcpretty
      - run:
          name: Report coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: v1-spm-deps-{{ checksum "Package.swift" }}
          paths:
            - .build
  Linux:
    docker:
      - image: nodesvapor/vapor-ci:swift-4.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-spm-deps-{{ checksum "Package.swift" }}
      - run:
          name: Copy Package file
          command: cp Package.swift res
      - run:
          name: Build and Run Tests
          no_output_timeout: 1800
          command: |
            swift test -Xswiftc -DNOJSON
      - run:
          name: Restoring Package file
          command: mv res Package.swift
      - save_cache:
          key: v2-spm-deps-{{ checksum "Package.swift" }}
          paths:
            - .build
workflows:
  version: 2
  build-and-test:
    jobs:
      - MacOS
      - Linux
experimental:
  notify:
    branches:
      only:
        - master
        - develop
