on: release
name: Auto docs
jobs:
  jazzyDocs:
    name: Jazzy docs
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Generate docs
        uses: nodes-vapor/github-actions/actions/jazzy-docs@develop
        with:
          target: AdminPanel
          commit_msg: Update Jazzy docs 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SOURCEKITTEN_REVISION: 0.24.0
          JAZZY_VERSION: 0.10.0